version: "3.9"  
services:
    client:
        image: node:24-alpine3.21
        ports:
            - "3000:3000"
    server:
        image: golang:trixie
        ports:
            - "8080:8080"
        environment:
            - name=value

    db:
        image: mysql:9.4.0
        restart: always
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
            MYSQL_DATABASE: Listedd
